### ISSUE TITLE
Please fix some bug ur brain

### ISSUE THREAD

**Issue by Garry050** [AureoleArk/Me#3]
- very slow your work progress
- always attacking me about my face and name <s>fucking stupid stop it</s>
- stop change name on Discord group

<img src=https://i.ppn.pw/cc/645ca6c4/j7a933b20.png>

**Comment by yudecchi** [comment]
It cannot be fixed (i think)

**Comment by AureoleArk** [comment]
Omaera iikagen ni shiro (reply to half years old comment)
